### ISSUE TITLE
[step4.a] PostRepositoryからの投稿詳細取得の改良

### ISSUE THREAD

**Issue by bird0401** [givery-bootcamp/dena-2024-team9#47]
PostRepositoryから投稿詳細を取得するメソッドの引数に includeComment boolを追加してください。
includeComment = trueが指定された場合、返り値のPostにコメント配列を含めるようにしてください。

コメント配列の順序はidの昇順とします。

改良後は投稿詳細取得のusecaseではコメント一覧も含めるようにしてください。

https://github.com/givery-bootcamp/training-app-2024/issues/20

**Comment by Y2-2** [comment]
https://github.com/givery-bootcamp/dena-2024-team9/issues/41
ここで一緒に実装します
