### ISSUE TITLE
[meeting.a]intentionのCRD作成

### ISSUE THREAD

**Issue by chocono2230** [givery-bootcamp/dena-2024-team9#71]
intentionテーブルを作成し、作成・読み込み・削除ができるようにする
更新処理(`PUT`)は必要ない。また、削除についても実質`POST`の中で行う

- GET /intention/{post_id}?state=””
  - post_idとstateに一致したユーザ情報[]を返却する
    - 不正なstate(`attend`, `skip`ではないもの)を弾く(400)
    - ユーザ情報：少なくともid,nameを含む(他の仕様はフロントのやりやすい形に)
- POST /intention/{post_id}
  - body
    - state: string(`attend` or `skip`)
    - user_id: number
  - post_id に対して、ユーザがstate(参加・不参加)の意思表明する
  - 多重登録や、複数ステータスを単一ユーザ・ミーティングに持つ状態は防止する
  - すでに登録されているstateの場合、物理削除する（(不)参加->(不)参加取り消し みたいな感じ）
  - 不正なpost_id、state、user_idも弾く

**Comment by bird0401** [comment]
テーブル名は全て複数形になっていたので、テーブル名はintentionではなくintentionsとして作成
