### ISSUE TITLE
[meeting.a]MeetingPostの中に、参加・不参加ボタンと参加者・不参加者一覧を追加

### ISSUE THREAD

**Issue by Marie673** [givery-bootcamp/dena-2024-team9#83]
サーバー側のエンドポイントあった方が良くない？

**Comment by chocono2230** [comment]
一応こっちでサーバ側の実装は書いてあって
https://github.com/givery-bootcamp/dena-2024-team9/issues/71
フロント側の使い方も書いたつもりだった
https://github.com/givery-bootcamp/dena-2024-team9/issues/72

問題点がわかってないから、もう少し詳細にお願いします🙏

**Comment by Marie673** [comment]
あ、それでいいね
